"use client";
import { useEffect,useState } from 'react';
import Link from 'next/link';
import AdminShell from '@/components/hb/AdminShell';
export default function SettingsPage(){
 const [s,setS]=useState(null),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/admin/settings').then(r=>r.json()).then(d=>d.ok?setS(d.settings):setError(d.error||'Unable to load settings'));},[]);
 function set(k,v){setS(x=>({...x,[k]:v}));setSaved(false)}
 async function save(e){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)});const d=await r.json();if(!d.ok)setError(d.error);else setSaved(true);setBusy(false)}
 if(!s)return <AdminShell title="Store settings"><div className="bg-white border rounded-xl p-8">{error||'Loading...'}</div></AdminShell>;
 const fields=[['brand_name','Brand name'],['support_email','Support email'],['support_phone','Support phone'],['whatsapp_number','WhatsApp'],['business_hours','Business hours'],['business_address','Business address'],['instagram_url','Instagram URL'],['facebook_url','Facebook URL'],['cod_fee','COD fee'],['shipping_fee','Shipping fee'],['free_shipping_threshold','Free shipping threshold'],['low_stock_threshold','Low stock threshold']];
 return <AdminShell title="Store settings"><section className="bg-white border border-neutral-200 rounded-xl overflow-hidden"><div className="p-5 border-b flex items-center justify-between"><div><h2 className="font-bold text-lg">Store configuration</h2><p className="text-xs text-neutral-400 mt-1">Changes are live on the storefront</p></div><Link href="/admin" className="text-xs font-bold underline">DASHBOARD</Link></div><form onSubmit={save} className="p-5 md:p-7 grid md:grid-cols-2 gap-5">{fields.map(([k,l])=><label key={k} className="text-[10px] font-black uppercase tracking-widest text-neutral-500">{l}<input value={s[k]??''} onChange={e=>set(k,e.target.value)} className="mt-2 w-full border border-neutral-200 rounded-lg px-3 py-3 text-sm text-neutral-900 focus:outline-none focus:ring-2 focus:ring-orange-400"/></label>)}<label className="text-[10px] font-black uppercase tracking-widest text-neutral-500 md:col-span-2">Announcement<textarea value={s.announcement_text||''} onChange={e=>set('announcement_text',e.target.value)} rows={3} className="mt-2 w-full border rounded-lg px-3 py-3 text-sm"/></label><label className="text-[10px] font-black uppercase tracking-widest text-neutral-500 md:col-span-2">Return policy<textarea value={s.return_policy_text||''} onChange={e=>set('return_policy_text',e.target.value)} rows={4} className="mt-2 w-full border rounded-lg px-3 py-3 text-sm"/></label>{error&&<div className="md:col-span-2 bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">{error}</div>}{saved&&<div className="md:col-span-2 bg-green-50 border border-green-200 text-green-700 px-4 py-3 text-sm">Settings saved successfully.</div>}<div className="md:col-span-2 flex justify-end"><button disabled={busy} className="bg-black text-white px-7 py-3.5 rounded-lg font-black text-sm disabled:opacity-50">{busy?'SAVING...':'SAVE CHANGES'}</button></div></form></section></AdminShell>
}
