"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ImagePlus, Plus, Trash2, Upload, Check, AlertCircle } from "lucide-react";
const SIZES=["S","M","L","XL","XXL","3XL"];
function slugify(v){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
function toRows(product){const by={};for(const v of product?.variants||[]){by[v.color] ||= {color:v.color,colorHex:v.colorHex||'#111111',stocks:{},images:product?.colorImages?.[v.color]||[]};by[v.color].stocks[v.size]=v.stock;}return Object.values(by).length?Object.values(by):[{color:'Black',colorHex:'#111111',stocks:{},images:[]}]}
export default function ProductForm({categories,product}){
 const router=useRouter(); const [name,setName]=useState(product?.name||''); const [slug,setSlug]=useState(product?.slug||''); const [sku,setSku]=useState(product?.sku||''); const [categoryId,setCategoryId]=useState(product?.categoryId||categories[0]?.id||''); const [price,setPrice]=useState(product?.price||''); const [mrp,setMrp]=useState(product?.mrp||''); const [status,setStatus]=useState(product?.status||'draft'); const [description,setDescription]=useState(product?.description||''); const [tags,setTags]=useState((product?.tags||[]).join(', ')); const [features,setFeatures]=useState((product?.features||[]).join('\n')); const [images,setImages]=useState((product?.images||[]).join('\n')); const [rows,setRows]=useState(toRows(product)); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [slugTouched,setSlugTouched]=useState(Boolean(product));
 const totalStock=useMemo(()=>rows.reduce((s,r)=>s+Object.values(r.stocks).reduce((a,n)=>a+Number(n||0),0),0),[rows]);
 function updateRow(i,key,val){setRows(rs=>rs.map((r,j)=>j===i?{...r,[key]:val}:r));}
 function updateStock(i,size,val){setRows(rs=>rs.map((r,j)=>j===i?{...r,stocks:{...r.stocks,[size]:val}}:r));}
 function addRow(){setRows(rs=>[...rs,{color:'',colorHex:'#111111',stocks:{},images:[]}]);}
 function removeRow(i){setRows(rs=>rs.filter((_,j)=>j!==i));}
 async function upload(e){const files=[...(e.target.files||[])];if(!files.length)return;setError('');const urls=[];for(const file of files){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const d=await r.json();if(!d.ok){setError(d.error||'Upload failed');continue;}urls.push(d.url);}if(urls.length)setImages(v=>[v,...urls].filter(Boolean).join('\n'));e.target.value='';}
 async function uploadColorImages(i,e){const files=[...(e.target.files||[])];if(!files.length)return;setError('');const urls=[];for(const file of files){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const d=await r.json();if(!d.ok){setError(d.error||'Upload failed');continue;}urls.push(d.url);}if(urls.length)setRows(rs=>rs.map((r,j)=>j===i?{...r,images:[...(r.images||[]),...urls]}:r));e.target.value='';}
 async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');const variants=[];for(const r of rows){if(!r.color.trim())continue;for(const size of SIZES){variants.push({color:r.color,colorHex:r.colorHex,size,stock:Number(r.stocks[size]||0),sku:`${sku}-${r.color.slice(0,3).toUpperCase()}-${size}`});}}if(!name||!sku||!categoryId||price===''){setError('Complete the required product fields.');setBusy(false);return;}const colorImages={};for(const r of rows){if(r.color.trim()&&(r.images||[]).length)colorImages[r.color.trim()]=r.images.filter(Boolean);}const body={name,slug,sku,categoryId,price,mrp,status,description,tags:tags.split(',').map(s=>s.trim()).filter(Boolean),features:features.split('\n').map(s=>s.trim()).filter(Boolean),images:images.split('\n').map(s=>s.trim()).filter(Boolean),colorImages,variants};try{const url=product?`/api/admin/products/${product.id}`:'/api/admin/products';const r=await fetch(url,{method:product?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!d.ok)throw new Error(d.error||'Could not save product');setMessage('Product saved successfully.');setTimeout(()=>router.push('/admin/products'),500);}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <form onSubmit={save} className="space-y-7">
  <div className="grid lg:grid-cols-[1.4fr_1fr] gap-6">
   <section className="space-y-5"><div><h3 className="font-bold text-lg">Basic information</h3><p className="text-xs text-neutral-400 mt-1">The information customers see on the product page.</p></div>
    <div className="grid md:grid-cols-2 gap-4"><label className="field">Product name <span>*</span><input required value={name} onChange={e=>{setName(e.target.value);if(!slugTouched)setSlug(slugify(e.target.value))}} placeholder="e.g. Performance Track Pant"/></label><label className="field">SKU <span>*</span><input required value={sku} onChange={e=>setSku(e.target.value.toUpperCase())} placeholder="HB-TP-001"/></label><label className="field">URL slug <input required value={slug} onChange={e=>{setSlugTouched(true);setSlug(slugify(e.target.value))}} placeholder="performance-track-pant"/></label><label className="field">Category <span>*</span><select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
    <div className="grid md:grid-cols-3 gap-4"><label className="field">Selling price <span>*</span><div className="price-input"><b>₹</b><input required type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} /></div></label><label className="field">MRP<div className="price-input"><b>₹</b><input type="number" min="0" value={mrp} onChange={e=>setMrp(e.target.value)} /></div></label><label className="field">Status <select value={status} onChange={e=>setStatus(e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div>
    <label className="field">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={6} placeholder="Fabric, fit, use case, care instructions..."/></label>
    <div className="grid md:grid-cols-2 gap-4"><label className="field">Search tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="track pants, gym, activewear"/><small>Separate tags with commas.</small></label><label className="field">Product features<textarea value={features} onChange={e=>setFeatures(e.target.value)} rows={4} placeholder={'4-way stretch\nMoisture wicking\nZip pockets'}/><small>One feature per line.</small></label></div>
   </section>
   <section className="bg-neutral-50 border rounded-xl p-5 h-fit"><div className="flex items-center justify-between"><div><h3 className="font-bold">Product media</h3><p className="text-xs text-neutral-400 mt-1">Add your product photos</p></div><label className="cursor-pointer bg-black text-white px-4 py-2 rounded-lg text-xs font-bold flex gap-2 items-center"><Upload size={15}/> ADD IMAGES<input type="file" multiple accept="image/*" onChange={upload} className="hidden"/></label></div><div className="mt-4 grid grid-cols-2 gap-3">{images.split('\n').map(s=>s.trim()).filter(Boolean).map((src,i)=><div key={`${src}-${i}`} className="aspect-square bg-white border rounded-lg overflow-hidden"><img src={src} alt="" className="w-full h-full object-cover"/></div>)}{!images.trim()&&<div className="col-span-2 aspect-video border border-dashed rounded-lg flex flex-col items-center justify-center text-neutral-400"><ImagePlus/><span className="text-xs mt-2">No images yet</span></div>}</div><textarea value={images} onChange={e=>setImages(e.target.value)} rows={3} placeholder="Or paste image URLs, one per line" className="mt-4 w-full border rounded-lg px-3 py-2 text-xs"/></section>
  </div>
  <section className="border rounded-xl overflow-hidden"><div className="p-5 bg-neutral-50 border-b flex flex-wrap gap-4 items-center justify-between"><div><h3 className="font-bold">Variants & inventory</h3><p className="text-xs text-neutral-400 mt-1">Set stock for every colour and size. Total: <b className="text-neutral-900">{totalStock}</b> units.</p></div><button type="button" onClick={addRow} className="border bg-white px-4 py-2 rounded-lg text-xs font-bold flex items-center gap-1"><Plus size={15}/> ADD COLOUR</button></div><div className="overflow-x-auto"><table className="w-full text-xs min-w-[900px]"><thead><tr className="bg-white text-neutral-400 uppercase tracking-widest"><th className="p-3 text-left">Colour</th><th className="p-3">Swatch</th><th className="p-3">Colour photos</th>{SIZES.map(s=><th key={s} className="p-3">{s}</th>)}<th/></tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t"><td className="p-3"><input value={r.color} onChange={e=>updateRow(i,'color',e.target.value)} placeholder="Black" className="border rounded px-2 py-2 w-32"/></td><td className="p-3"><input type="color" value={r.colorHex} onChange={e=>updateRow(i,'colorHex',e.target.value)} className="w-9 h-9 p-0 border rounded"/></td><td className="p-3"><label className="cursor-pointer inline-flex items-center gap-1 border rounded px-2 py-2 bg-white font-bold"><Upload size={13}/> PHOTOS<input type="file" multiple accept="image/*" onChange={e=>uploadColorImages(i,e)} className="hidden"/></label><div className="flex gap-1 mt-2">{(r.images||[]).map((src,k)=><div key={src+k} className="relative w-10 h-10"><img src={src} className="w-full h-full object-cover rounded border"/><button type="button" onClick={()=>setRows(rs=>rs.map((x,j)=>j===i?{...x,images:x.images.filter((_,xk)=>xk!==k)}:x))} className="absolute -top-1 -right-1 bg-black text-white rounded-full w-4 h-4 text-[9px]">×</button></div>)}</div></td>{SIZES.map(s=><td key={s} className="p-2"><input type="number" min="0" value={r.stocks[s]??''} onChange={e=>updateStock(i,s,e.target.value)} className="w-16 border rounded px-2 py-2 text-center"/></td>)}<td className="p-3"><button type="button" onClick={()=>removeRow(i)} className="text-red-600" title="Remove colour"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></section>
  {error&&<div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm flex gap-2"><AlertCircle size={18}/>{error}</div>}{message&&<div className="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded-lg text-sm flex gap-2"><Check size={18}/>{message}</div>}
  <div className="sticky bottom-0 bg-white/95 backdrop-blur border-t py-4 flex items-center justify-between"><div className="text-xs text-neutral-400">{totalStock} units configured · {status}</div><div className="flex gap-3"><button type="button" onClick={()=>router.push('/admin/products')} className="border px-5 py-3 rounded-lg font-bold text-sm">CANCEL</button><button disabled={busy} className="bg-black text-white px-7 py-3 rounded-lg font-black text-sm disabled:opacity-40">{busy?'SAVING...':product?'SAVE PRODUCT':'CREATE PRODUCT'}</button></div></div>
  <style jsx>{`.field{display:block;font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#525252}.field span{color:#ea580c}.field input,.field select,.field textarea{display:block;width:100%;margin-top:7px;border:1px solid #e5e5e5;border-radius:8px;padding:11px 12px;font-size:14px;font-weight:500;letter-spacing:normal;text-transform:none;outline:none;background:#fff}.field input:focus,.field select:focus,.field textarea:focus{border-color:#f97316;box-shadow:0 0 0 2px #fed7aa}.field small{display:block;margin-top:5px;color:#a3a3a3;font-size:10px;text-transform:none;letter-spacing:normal}.price-input{display:flex;align-items:center;background:#fff;border:1px solid #e5e5e5;border-radius:8px;margin-top:7px}.price-input b{padding-left:12px}.price-input input{border:0!important;margin:0!important;box-shadow:none!important}`}</style>
 </form>
}
